name: PR Flow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Compile Java
      run: lein javac
    - name: Coverage
      run: lein coverage
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./target/coverage/codecov.json
    - name: Run Java Tests
      run: lein pom && mvn test --batch-mode --fail-at-end
    - name: Unit tests in Clojure
      run: lein junit
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: 'target/surefire-reports/*.xml'
