name: PR Flow

on:
  pull_request:
    branches: [ master ]

env:
  TEST_REPORT_JUNIT_XML_OUTPUT_DIR: target/surefire-reports

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Compile Java
      run: lein javac
    - name: Coverage
      run: lein coverage
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./target/coverage/codecov.json
    - name: Run Java Tests
      run: lein pom && mvn test --batch-mode --fail-at-end
    - name: Unit tests in Clojure
      run: lein test
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit